/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const formatCostFixed: typeof import('@/utils/format')['formatCostFixed']
  const formatCountdown: typeof import('@/utils/format')['formatCountdown']
  const formatCountdownWithSuffix: typeof import('@/utils/format')['formatCountdownWithSuffix']
  const formatCurrency: typeof import('@/utils/format')['formatCurrency']
  const formatDate: typeof import('@/utils/format')['formatDate']
  const formatDateOnly: typeof import('@/utils/format')['formatDateOnly']
  const formatDateTime: typeof import('@/utils/format')['formatDateTime']
  const formatNumber: typeof import('@/utils/format')['formatNumber']
  const formatRelativeTime: typeof import('@/utils/format')['formatRelativeTime']
  const getDaysRemaining: typeof import('@/utils/format')['getDaysRemaining']
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly formatCostFixed: UnwrapRef<typeof import('@/utils/format')['formatCostFixed']>
    readonly formatCountdown: UnwrapRef<typeof import('@/utils/format')['formatCountdown']>
    readonly formatCountdownWithSuffix: UnwrapRef<typeof import('@/utils/format')['formatCountdownWithSuffix']>
    readonly formatCurrency: UnwrapRef<typeof import('@/utils/format')['formatCurrency']>
    readonly formatDate: UnwrapRef<typeof import('@/utils/format')['formatDate']>
    readonly formatDateOnly: UnwrapRef<typeof import('@/utils/format')['formatDateOnly']>
    readonly formatDateTime: UnwrapRef<typeof import('@/utils/format')['formatDateTime']>
    readonly formatNumber: UnwrapRef<typeof import('@/utils/format')['formatNumber']>
    readonly formatRelativeTime: UnwrapRef<typeof import('@/utils/format')['formatRelativeTime']>
    readonly getDaysRemaining: UnwrapRef<typeof import('@/utils/format')['getDaysRemaining']>
  }
}